apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: synapse            # e.g., flashmaster
type: Opaque
stringData:
  DATABASE_URL: ""postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST_PRIVATE}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}""
  DO_SPACES_KEY: "DO00LMB24WZXVCMK6G22"
  DO_SPACES_SECRET: "iF+p6XAKezSNNCKsIB3f0XGS+6/gmDE+8VPZCyyBU1o"
  DIGITALOCEAN_MODEL_KEY: "sk-do-uthd1l4FYE-EUeITacHO9LHOFFJnHdVNdio21yT07SwyDyg3yIa0ip4dOa"


