apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: synapse-ingress
  namespace: synapse
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: synapse.shtrial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse-web
                port:
                  number: 80
    - host: api.synapse.shtrial.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: synapse-api
                port:
                  number: 80

