apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ${APP_SLUG}
type: Opaque
stringData:
  DATABASE_URL: "${DATABASE_URL}"
  DO_SPACES_KEY: "${DO_SPACES_KEY}"
  DO_SPACES_SECRET: "${DO_SPACES_SECRET}"
  DIGITALOCEAN_MODEL_KEY: "${DIGITALOCEAN_MODEL_KEY}"

