apiVersion: v1
kind: Service
metadata:
  name: synapse-backend
  namespace: synapse
spec:
  type: ClusterIP
  selector:
    app: synapse-backend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP

