apiVersion: v1
kind: Service
metadata:
  name: synapse-frontend
  namespace: synapse
spec:
  type: ClusterIP
  selector:
    app: synapse-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
