apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: ${APP_SLUG}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: '10m'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '${APP_SLUG}.${APP_DOMAIN_BASE}'
        - 'api-${APP_SLUG}.${APP_DOMAIN_BASE}'
      secretName: wildcard-shtrial-tls # Points to shared secret
  rules:
    - host: '${APP_SLUG}.${APP_DOMAIN_BASE}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: 'api-${APP_SLUG}.${APP_DOMAIN_BASE}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
