apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-frontend
  namespace: synapse
  labels:
    app: synapse-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synapse-frontend
  template:
    metadata:
      labels:
        app: synapse-frontend
    spec:
      containers:
      - name: synapse-frontend
        image: registry.digitalocean.com/shtrial-reg/synapse-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api-synapse.shtrial.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-backend
  namespace: synapse
  labels:
    app: synapse-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: synapse-backend
  template:
    metadata:
      labels:
        app: synapse-backend
    spec:
      containers:
      - name: synapse-backend
        image: registry.digitalocean.com/shtrial-reg/synapse-backend:latest
        ports:
        - containerPort: 8000
